spring:
  application:
    name: hello-spring-cloud-netfix-zuul
  boot:
    admin:
      client:
        url: http://localhost:8500
  zipkin:
    base-url: http://localhost:8400

server:
  port: 8300

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    api-admin:
      path: /admin/**
      serviceId: hello-spring-cloud-netflix-web-admin-feign