spring:
  application:
    name: hello-spring-cloud-netflix-service-admin
  boot:
    admin:
      client:
        url: http://192.168.126.130:8084
  zipkin:
    base-url: http://192.168.126.130:9411


server:
  port: 8500
  # port: 8501

mybatis:
  type-aliases-package: com.antoniopeng.hello.spring.cloud.netflix.service.admin.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.126.130:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info