spring:
  application:
    name: hello-spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8500

server:
  port: 8400

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    web:
      server:
        auto-time-requests: false