spring:
  application:
    name: hello-spring-cloud-netflix-service-admin
  boot:
    admin:
      client:
        url: http://localhost:8500
  zipkin:
    base-url: http://localhost:8400
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/hello_spring_cloud_netflix?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.antoniopeng.hello.spring.cloud.netflix.service.admin.domain
  mapper-locations: classpath:mapper/*.xml
  
server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/