spring:
  application:
    name: hello-spring-cloud-admin
  zipkin:
    base-url: http://localhost:8400

server:
  port: 8500

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info